repos:
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
        - id: check-toml
        - id: check-ast
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-json
        - id: pretty-format-json
        - id: debug-statements
        - id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
        - id: black
